rackerlabs/base-image-blueprints

Gentoo_PVHVM-2.sh

Was more explicit on eselect usage, which can vary over time.  I assumed you wanted what I selected as it's what users generally want.  Would be nice not to need python2.7 though :P
I also added better emerge / make options for build speed and completeness
Last thing I did was update the cloud init version.
If you need me to ammend or remove any of these commits, let me know.

Gentoo fixes

---

Ubuntu_15.04_Teeth_post.sh

update-grub generates a garbage grub config unless you're actually on
the booted hardware. Change out the root device to make it work.
Additionally, fix the e2label command to reference sda1, where the
partition is during build, rather than md126p1, where it will be.

Ensure grub config uses LABEL to find root part

---

CentOS_5.cfg
CentOS_6.cfg
CentOS_6_PVHVM.cfg
CentOS_6_PVHVM_Hadoop_Ambari.cfg
CentOS_7_PVHVM.cfg
CentOS_7_PVHVM_NovaAgent2.cfg
Red_Hat_Enterprise_Linux_5.cfg
Red_Hat_Enterprise_Linux_6.cfg
Red_Hat_Enterprise_Linux_6_PVHVM.cfg
Red_Hat_Enterprise_Linux_7_PVHVM.cfg
Scientific_Linux_6_PVHVM.cfg
Scientific_Linux_7_PVHVM.cfg

Fix for inadvertently blocking ipv6-icmp in CentOS/RHEL images

fix ip6tables to permit ipv6-icmp correctly

---

CentOS_5.cfg
CentOS_6.cfg
CentOS_6_PVHVM.cfg
CentOS_7_PVHVM.cfg
Red_Hat_Enterprise_Linux_6.cfg
Red_Hat_Enterprise_Linux_6_PVHVM.cfg
Red_Hat_Enterprise_Linux_7_PVHVM.cfg

Instead of replacing the contents of the log files in /var/log with a newline (which creates problems with btmp, at the very least), we should truncate them in place.

Fix for log file truncation issues

---

CentOS_7_PVHVM.cfg
Red_Hat_Enterprise_Linux_7_PVHVM.cfg

NetworkManager service was running alongside nova agent and causing dns to be empty

Fixing network manager service in RHEL

---

Ubuntu_14.04.cfg
Ubuntu_14.04_KVM.cfg
Ubuntu_14.04_PVHVM.cfg
Ubuntu_14.04_PVHVM_Heat.cfg
Ubuntu_14.04_Teeth.cfg
Ubuntu_14.04_Teeth_post.sh

This set of changes will correct the way we're handling the network interfaces file by using a preseed value instead of hacks which are no longer working.  This also corrects log truncation for the images, as well as setting/removing root's password.

Ubuntu 1404 fixes

---

CentOS_5.cfg
Red_Hat_Enterprise_Linux_5.cfg

Connection tracking was broken in RHEL/CentOS 5 kernels, so the rules we provided weren't being applied correctly.  This implements primitive connection tracking with rules provided by 'lokkit'

RHEL/CentOS 5 IPv6 firewall fixes

---

CentOS_7_PVHVM_Heat_post.sh

The current script does not correctly check for systemd therefore the service
is not being installed correctly. We can assume systemd is in use because this
is Cent7.

Modify Heat script for CentOS

---

CentOS_5.cfg
Red_Hat_Enterprise_Linux_5.cfg

Removed unneeded systemd stuff, cleaned up a few things, and switched over to using the repackaged nova-agent, which will resolve the RPM db errors in RHEL 5

Streamline the CentOS/RHEL 5 kicks and use the repackaged nova-agent

---

CentOS_7_PVHVM_Heat_post.sh
Ubuntu_14.04_PVHVM_Heat_post.sh

SoftwareDeployments in Heat stopped working due to this bug:
https://bugs.launchpad.net/heat-templates/+bug/1567584

Update os-collect-config on Heat images

---

Ubuntu_14.04_PVHVM_Heat_post.sh

For some reason, these aren't being pulled in by pip.  Here are the dependencies of the packages that aren't being pulled in:
```
os-collect-config -> oslo.config -> debtcollector -> [ wrapt, funcsigs ]
os-collect-config -> oslo.utils -> [ monotonic, pytz ]
os-collect-config -> python-keystoneclient -> positional
```
Not sure if we want to fix it like this or continue searching for the root cause.
I've verified this fix works in heat-ci:
https://github.com/rackerlabs/heat-ci/commit/65376562
I've found a pyrax bug report about this:
https://github.com/rackspace/pyrax/issues/570

Install pip dependencies on Ubuntu Heat image

---

Ubuntu_14.04_PVHVM_Heat_post.sh

Ubuntu/PIP comes with SetupTools 3.3.  The latest version of SetupTools is 21.2, and the version required for Ansible is anything higher than 11.3.

Upgrading setuptools version to fix issue with Ansible

---

Red_Hat_Enterprise_Linux_5.cfg
Red_Hat_Enterprise_Linux_6.cfg
Red_Hat_Enterprise_Linux_6_PVHVM.cfg
Red_Hat_Enterprise_Linux_7_PVHVM.cfg
Red_Hat_Enterprise_Linux_7_Teeth.cfg

Per request related to issues around RHEL 6.8 release, we're adding the sosreport package to RHEL images so that we can more quickly gather diagnostics for Red Hat Support.

Add sosreport package to RHEL kicks

---

CentOS_6_Teeth_post.sh
CentOS_7_Teeth.cfg
Debian_8_Teeth_post.sh
Debian_Testing_Teeth_post.sh
Debian_Unstable_Teeth_post.sh
Fedora_22_Teeth.cfg
Fedora_23_Teeth.cfg
Red_Hat_Enterprise_Linux_7_Teeth.cfg
Ubuntu_14.04_Teeth_post.sh
Ubuntu_15.10_Teeth_post.sh

We decided to drop our effort of adding password support to OM images awhile back. This is just updating the public repo to what is already reflected on our build servers.
This reverts commit b55f3a6a68de9902de9afc3a6ccd7dcffbf4a87c, reversing
changes made to 2c10730971fe9a83ca8680dc523f15fb1d3cdee4.

Revert "Merge pull request #37 from rackerlabs/add-OM-pw-support"

---

CentOS_6_PVHVM.cfg
Debian_7_PVHVM.cfg
Debian_7_PVHVM_post.sh
Debian_8_PVHVM.cfg
Debian_8_PVHVM_post.sh
Debian_Testing_PVHVM.cfg
Debian_Testing_PVHVM_post.sh
Debian_Unstable_PVHVM.cfg
Debian_Unstable_PVHVM_post.sh
Red_Hat_Enterprise_Linux_6_PVHVM.cfg
Scientific_Linux_6_PVHVM.cfg

Some of these images had ext3 fs still in the kick due to PV compatability.
However all of these PVHVM images can safely be moved to ext4 now.

Change leftover PVHVM ext3 fs to ext4

---

CentOS_6_Teeth_post.sh

On first boot, on CentOS6-Teeth IPv6 does not work until you do a
restart of the network service. Prior to this, the IPv6 address is set,
and routes are in place, but the network is unreachable, except, oddly,
the gateway.
After a network reset, everything works.
This is a work-around that just issues a network restart from the
cloud-init per-instance scripts. Ultimately, this may be kernel-related,
and we should check if this is still needed if we unpin the CentOS 6 kernel.
JIRA:IMG-240

Restart network on CentOS6-Teeth for IPv6

---

CentOS_6.cfg

Update CentOS_6.cfg to enable selinux in permissive mode

Update CentOS_6.cfg to enable selinux

---

Fedora_25_PVHVM.cfg

https://jira.rax.io/browse/IMG-370
The base image built from the Fedora 25 template failed the following cloud-init QC check on the instance:
```which zsh 2> /dev/null; if [ $? = 0 ]; then echo "cloud-init instance run was successful"; fi;```
Bug reference: https://bugzilla.redhat.com/show_bug.cgi?id=1447708

IMG-370 Upgrade cloud-init to patched version

---

Debian_7_PVHVM.cfg

Temporary revert to attempt to eliminate this change as the cause of the failures to boot Debian 7 instances.

DFOT-818 Revert blueprints changes

---

fedora_30_pvhvm.cfg

url needs to be at the top of the kickstart file.  All other ways fail on Fedora 30.
Added 'text' so that it doesn't default to a GUI.
python2-dnf no longer in upstream repos, and I don't believe it is needed.

DFOT-2973: Fedora 30 pvhvm update

---

centos_7_pvhvm.cfg
centos_7_pvhvm_heat.cfg
centos_8_pvhvm.cfg
fedora_29_pvhvm.cfg
fedora_30_pvhvm.cfg
redhat_7_pvhvm.cfg
redhat_8_pvhvm.cfg

Based on the Red Hat IO performance webinar I attended last wk

Switching to noop or none ioscheduler to save cycles

---

debian_9_pvhvm_heat.sh

Use upstream repo packages to match monitoring and backup agents

debian_9_pvhvm_heat rotate out xen guest utilities packages

---

debian_9_pvhvm_heat.sh

- nova-agent install removed due to duplicate with manditory img_config_drive

Debian 9 pvhvm heat: remove ospc and nova-agent install
