Ubuntu_12.04_Teeth_post.sh
Ubuntu_14.04_Teeth_post.sh

This fixes similar problems in these ubuntu builds that ubuntu 15.04
had. Hopefully with these changes the images will work on OnMetal v2.

Fixing likely problems with Ubu 12/14 kicks

---

Ubuntu_14.04_Teeth_v2.cfg
Ubuntu_14.04_Teeth_v2_post.sh

- Removed modifications made to existing image for v2 compatibility
- Created new kicks for v2 specifically that actually work

Separate v1 and v2 images for Ubu 14.04

---

CentOS_7_Teeth.cfg

Changes as documented in the wiki for OnMetal v2 CentOS 7 support:
https://one.rackspace.com/display/teeth/Intel+RSTe+Required+Images+Changes

OMv2 Changes for CentOS 7

---

CentOS_7_PVHVM_NovaAgent2.cfg

Here is the first shot at the new image.
Thanks!
Daniel

add image for centos with new novaagent

---

CentOS_6_Teeth_post.sh
CentOS_7_Teeth.cfg
Debian_8_Teeth_post.sh
Debian_Testing_Teeth_post.sh
Debian_Unstable_Teeth_post.sh
Fedora_22_Teeth.cfg
Fedora_23_Teeth.cfg
Ubuntu_14.04_Teeth_post.sh
Ubuntu_15.10_Teeth_post.sh

Updating OM images for OM v2

---

Red_Hat_Enterprise_Linux_6_VMware.cfg

vCloud requested that we remove the EPEL repo..  Took the opportunity to apply additional cleanup to the kick file while I was there.

Changes requested by vCloud team for RHEL 6

---

Red_Hat_Enterprise_Linux_7_Teeth.cfg

Adding RHEL7 Teeth image to repo

Add RHEL7 Teeth

---

CentOS_7_PVHVM_Heat_post.sh

Remove all conditionality surrounding '/etc/systemd/system/os-collect-config.service' file being written

Remove conditionality

---

Red_Hat_Enterprise_Linux_6_VMware.cfg

We need this repo to install pacakges such as cloud-init.

Readd epel repo to VMware image

---

CentOS_6_Teeth_post.sh
CentOS_7_Teeth.cfg
Debian_8_Teeth_post.sh
Debian_Testing_Teeth_post.sh
Debian_Unstable_Teeth_post.sh
Fedora_22_Teeth.cfg
Fedora_23_Teeth.cfg
Red_Hat_Enterprise_Linux_7_Teeth.cfg
Ubuntu_14.04_Teeth_post.sh
Ubuntu_15.10_Teeth_post.sh

With the corresponding code change to return a password through nova for
OnMetal images, we no longer need to lock out the root pw

Adding password support for OnMetal images

---

Debian_Testing_PVHVM.cfg
Debian_Testing_PVHVM_post.sh

Changes to get Debian testing (stretch) to build properly..  Mainly better systemd integration for nova-agent and corrected log truncation

Fixes for Debian Stretch

---

Ubuntu_14.04_Teeth_post.sh

Fixes network names switching on startup due to udev/systemd and biosdevname
Fixes a bug with cloud-init where it would not add networks if they started
with 'eth'

Ubuntu 14.04 OM: cloud-init and net names fix

---

CentOS_6_Teeth.cfg
CentOS_6_Teeth_post.sh
Scientific_Linux_6_PVHVM.cfg

Fixing a dependency issue in cloud-init took some reworking of several parts of the kick files.  While I was there I took the chance to clean up a few things too.

CentOS 6 OnMetal rework

---

Arch_PVHVM-2.sh

Changes from the November image refresh cycle

November image refresh

---

CentOS_6_PVHVM.cfg

Update CentOS_6_PVHVM.cfg to enable selinux in permissive mode

Update CentOS_6_PVHVM.cfg to enable selinux

---

CentOS_6.cfg

Update CentOS_6.cfg to enable selinux in permissive mode

Update CentOS_6.cfg to enable selinux

---

CentOS_6.cfg
CentOS_6_PVHVM.cfg
CentOS_7_PVHVM.cfg
Debian_7_PVHVM.cfg
Debian_7_PVHVM_post.sh
Debian_8_PVHVM.cfg
Debian_8_PVHVM_post.sh
Debian_9_PVHVM.cfg
Debian_9_PVHVM_post.sh
Fedora_25_PVHVM.cfg
Fedora_26_PVHVM.cfg
Red_Hat_Enterprise_Linux_6.cfg
Red_Hat_Enterprise_Linux_6_PVHVM.cfg
Red_Hat_Enterprise_Linux_7_PVHVM.cfg

- RHEL based images change nova-agent to use EPEL
- Update and cleanup Debian build templates

Update image build files

---

centos_6_pvhvm.cfg
centos_6_teeth.cfg
centos_6_teeth_post.sh
centos_7_pvhvm.cfg
centos_7_pvhvm_heat.cfg
centos_7_teeth.cfg
debian_7_pvhvm_post.sh
debian_7_teeth.cfg
debian_8_pvhvm_post.sh
debian_8_teeth.cfg
debian_9_pvhvm_post.sh
debian_9_teeth.cfg
debian_9_teeth_post.sh
fedora_26_pvhvm.cfg
fedora_26_teeth.cfg
fedora_27_pvhvm.cfg
fedora_27_teeth.cfg
red_hat_6_pvhvm.cfg
red_hat_7_pvhvm.cfg
ubuntu_14.04_teeth.cfg
ubuntu_14.04_teeth_post.sh

- Cleanup cloud-init config files that are placed on systems
- Make the cloud-init config file consistent across RHEL and Debian based systems
- Fix for networking for CentOS 6 Teeth

Image updates

---

centos_6_onmetal_post.sh
centos_7_onmetal.cfg
debian_8_onmetal_post.sh
debian_8_pvhvm_post.sh
debian_9_onmetal_post.sh
debian_9_pvhvm.cfg
fedora_27_onmetal.cfg
fedora_28_onmetal.cfg

- cloud-init and mount fixes for OnMetal images
- Update xe-guest-utilities package for Debian 9

Updates to base images

---

debian_8_pvhvm.cfg
debian_9_pvhvm.cfg

Moved nova-agent install to Post process until artifactory is ready for debian repo.

Fix Debian 8 and 9 build processes

---

centos_8_pvhvm.cfg

- Remove extra space lines 105+
- Manually install nova-agent from github
- Update to use KICK_HOST
- Fix repo urls
- cloud-utils no longer exists in upstream repos
- fix EOF syntax

CentOS 8 pvhvm 4th attempt (manual nova-agent)

---

fedora_31_onmetal.cfg
fedora_31_pvhvm.cfg

JIRA:DFOT-3360 Adding kickstart files for Fedora 31

---

centos_8_pvhvm.cfg

fixed tabbing for options on network and growpart.

Fixed centos_8_pvhvm cloud-init config

---

centos_7_pvhvm_heat_post.py

Two main things in this update:
1) Removes the dependency on the git module
2) Versioning the module installs

Fix centos 7 HEAT post config
